name: macOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: cache Homebrew cache
            uses: actions/cache@v2
            with:
              path: /Users/runner/Library/Caches/Homebrew
              key: ${{ runner.os }}-sbt-${{ hashFiles('*.rb') }}

    - name: brew update
      run: brew update
    - name: tap riscv
      run: brew tap riscv/riscv
    - name: install tools
      run: brew install riscv-tools
    - name: test
      run: brew test riscv-tools
